apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: smeeclient-build
spec:
  params:
  - default: https://github.com/geoffrey-pascal/smeeclient-nodejs.git
    name: git
    type: string
  - default: master
    name: git_branch
    type: string
  - default: "12"
    name: nodejs_ver
    type: string
  - default: quay.io/schabrolles/smeeclient_ppc64le:stable
    name: image
    type: string
  tasks:
  - name: git-clone
    params:
    - name: url
      value: $(params.git)
    - name: revision
      value: $(params.git_branch)
    - name: submodules
      value: "true"
    - name: depth
      value: "1"
    - name: sslVerify
      value: "true"
    - name: deleteExisting
      value: "true"
    - name: verbose
      value: "true"
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: smee
  - name: s2i-nodejs
    params:
    - name: VERSION
      value: $(params.nodejs_ver)
    - name: PATH_CONTEXT
      value: .
    - name: TLSVERIFY
      value: "false"
    - name: IMAGE
      value: $(params.image)
    runAfter:
    - git-clone
    taskRef:
      kind: ClusterTask
      name: s2i-nodejs
    workspaces:
    - name: source
      workspace: smee
  workspaces:
  - name: smee
