kind: Deployment
apiVersion: apps/v1
metadata:
  name: smeeclient-{{ include "sushiweb.fullname" . }}
  labels:
    app: smeeclient-{{ include "sushiweb.fullname" . }}
    app.kubernetes.io/component: smeeclient-{{ include "sushiweb.fullname" . }}
    app.kubernetes.io/instance: smeeclient-{{ include "sushiweb.fullname" . }}
    app.kubernetes.io/part-of: Triggers
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: smeeclient-{{ include "sushiweb.fullname" . }}
  template:
    metadata:
      labels:
        deployment: smeeclient-{{ include "sushiweb.fullname" . }}
    spec:
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: smeeclient
          env:
            - name: SMEESOURCE
              value: {{ .Values.smee.smeeSource }}
            - name: HTTPTARGET
              value: 'http://el-event-listener-{{ include "sushiweb.fullname" . }}:8080'
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: '0'
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          image: {{ .Values.smee.smeeImage }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600