apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: event-listener-{{ include "sushiweb.fullname" . }}
  finalizers:
    - eventlisteners.triggers.tekton.dev
spec:
  namespaceSelector: {}
  podTemplate: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: github-withref-push
      interceptors:
        - cel:
            filter: 'has(body.ref) && body.ref.split(''/'')[2] == ''{{ .Values.git.revision }}'''
            overlays:
              - expression: 'body.ref.split(''/'')[2]'
                key: branch_name
      name: build-on-branch
      template:
        ref: trigger-template-{{ include "sushiweb.fullname" . }}-git
    - bindings:
        - kind: TriggerBinding
          ref: github-withref-newtag
      interceptors:
        - cel:
            filter: 'has(body.ref) && body.ref.split(''/'')[1] == ''tags'''
            overlays:
              - expression: 'body.ref.split(''/'')[2]'
                key: tag-name
      name: build-on-tag
      template:
        ref: trigger-template-{{ include "sushiweb.fullname" . }}-git-tag