apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ include "sushiweb.fullname" . }}
    app.kubernetes.io/component: {{ include "sushiweb.fullname" . }}
    app.kubernetes.io/instance: {{ include "sushiweb.fullname" . }}
  name: {{ include "sushiweb.fullname" . }}
spec:
  port:
    targetPort: {{ .Values.service.port }}-tcp
  to:
    kind: Service
    name: {{ include "sushiweb.fullname" . }}
    weight: 100
  wildcardPolicy: None