apiVersion: v1
kind: Service
metadata:
  name: {{ include "sushiweb.fullname" . }}
  labels:
    {{- include "sushiweb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: {{ .Values.service.port }}-tcp
  selector:
    {{- include "sushiweb.selectorLabels" . | nindent 4 }}
